#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scons
Version  : 3.0.1
Release  : 25
URL      : https://sourceforge.net/projects/scons/files/scons/3.0.1/scons-3.0.1.tar.gz
Source0  : https://sourceforge.net/projects/scons/files/scons/3.0.1/scons-3.0.1.tar.gz
Summary  : Open Source next-generation build tool.
Group    : Development/Tools
License  : MIT
Requires: scons-bin = %{version}-%{release}
Requires: scons-license = %{version}-%{release}
Requires: scons-man = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
Patch1: manpage.patch
Patch2: py2.patch

%description
Improved, cross-platform substitute for the classic Make
        utility.  In short, SCons is an easier, more reliable
        and faster way to build software.

%package bin
Summary: bin components for the scons package.
Group: Binaries
Requires: scons-license = %{version}-%{release}
Requires: scons-man = %{version}-%{release}

%description bin
bin components for the scons package.


%package license
Summary: license components for the scons package.
Group: Default

%description license
license components for the scons package.


%package man
Summary: man components for the scons package.
Group: Default

%description man
man components for the scons package.


%prep
%setup -q -n scons-3.0.1
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545262518
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scons
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/scons/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}
## install_append content
find %{buildroot} -name "*.pyc" | xargs rm
## install_append end

%files
%defattr(-,root,root,-)
/usr/lib/scons-3.0.1/SCons/Action.py
/usr/lib/scons-3.0.1/SCons/Builder.py
/usr/lib/scons-3.0.1/SCons/CacheDir.py
/usr/lib/scons-3.0.1/SCons/Conftest.py
/usr/lib/scons-3.0.1/SCons/Debug.py
/usr/lib/scons-3.0.1/SCons/Defaults.py
/usr/lib/scons-3.0.1/SCons/Environment.py
/usr/lib/scons-3.0.1/SCons/Errors.py
/usr/lib/scons-3.0.1/SCons/Executor.py
/usr/lib/scons-3.0.1/SCons/Job.py
/usr/lib/scons-3.0.1/SCons/Memoize.py
/usr/lib/scons-3.0.1/SCons/Node/Alias.py
/usr/lib/scons-3.0.1/SCons/Node/FS.py
/usr/lib/scons-3.0.1/SCons/Node/Python.py
/usr/lib/scons-3.0.1/SCons/Node/__init__.py
/usr/lib/scons-3.0.1/SCons/Options/BoolOption.py
/usr/lib/scons-3.0.1/SCons/Options/EnumOption.py
/usr/lib/scons-3.0.1/SCons/Options/ListOption.py
/usr/lib/scons-3.0.1/SCons/Options/PackageOption.py
/usr/lib/scons-3.0.1/SCons/Options/PathOption.py
/usr/lib/scons-3.0.1/SCons/Options/__init__.py
/usr/lib/scons-3.0.1/SCons/PathList.py
/usr/lib/scons-3.0.1/SCons/Platform/__init__.py
/usr/lib/scons-3.0.1/SCons/Platform/aix.py
/usr/lib/scons-3.0.1/SCons/Platform/cygwin.py
/usr/lib/scons-3.0.1/SCons/Platform/darwin.py
/usr/lib/scons-3.0.1/SCons/Platform/hpux.py
/usr/lib/scons-3.0.1/SCons/Platform/irix.py
/usr/lib/scons-3.0.1/SCons/Platform/os2.py
/usr/lib/scons-3.0.1/SCons/Platform/posix.py
/usr/lib/scons-3.0.1/SCons/Platform/sunos.py
/usr/lib/scons-3.0.1/SCons/Platform/win32.py
/usr/lib/scons-3.0.1/SCons/SConf.py
/usr/lib/scons-3.0.1/SCons/SConsign.py
/usr/lib/scons-3.0.1/SCons/Scanner/C.py
/usr/lib/scons-3.0.1/SCons/Scanner/D.py
/usr/lib/scons-3.0.1/SCons/Scanner/Dir.py
/usr/lib/scons-3.0.1/SCons/Scanner/Fortran.py
/usr/lib/scons-3.0.1/SCons/Scanner/IDL.py
/usr/lib/scons-3.0.1/SCons/Scanner/LaTeX.py
/usr/lib/scons-3.0.1/SCons/Scanner/Prog.py
/usr/lib/scons-3.0.1/SCons/Scanner/RC.py
/usr/lib/scons-3.0.1/SCons/Scanner/SWIG.py
/usr/lib/scons-3.0.1/SCons/Scanner/__init__.py
/usr/lib/scons-3.0.1/SCons/Script/Interactive.py
/usr/lib/scons-3.0.1/SCons/Script/Main.py
/usr/lib/scons-3.0.1/SCons/Script/SConsOptions.py
/usr/lib/scons-3.0.1/SCons/Script/SConscript.py
/usr/lib/scons-3.0.1/SCons/Script/__init__.py
/usr/lib/scons-3.0.1/SCons/Subst.py
/usr/lib/scons-3.0.1/SCons/Taskmaster.py
/usr/lib/scons-3.0.1/SCons/Tool/386asm.py
/usr/lib/scons-3.0.1/SCons/Tool/DCommon.py
/usr/lib/scons-3.0.1/SCons/Tool/FortranCommon.py
/usr/lib/scons-3.0.1/SCons/Tool/GettextCommon.py
/usr/lib/scons-3.0.1/SCons/Tool/JavaCommon.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/__init__.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/arch.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/common.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/netframework.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/sdk.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/vc.py
/usr/lib/scons-3.0.1/SCons/Tool/MSCommon/vs.py
/usr/lib/scons-3.0.1/SCons/Tool/PharLapCommon.py
/usr/lib/scons-3.0.1/SCons/Tool/__init__.py
/usr/lib/scons-3.0.1/SCons/Tool/aixc++.py
/usr/lib/scons-3.0.1/SCons/Tool/aixcc.py
/usr/lib/scons-3.0.1/SCons/Tool/aixcxx.py
/usr/lib/scons-3.0.1/SCons/Tool/aixf77.py
/usr/lib/scons-3.0.1/SCons/Tool/aixlink.py
/usr/lib/scons-3.0.1/SCons/Tool/applelink.py
/usr/lib/scons-3.0.1/SCons/Tool/ar.py
/usr/lib/scons-3.0.1/SCons/Tool/as.py
/usr/lib/scons-3.0.1/SCons/Tool/bcc32.py
/usr/lib/scons-3.0.1/SCons/Tool/c++.py
/usr/lib/scons-3.0.1/SCons/Tool/cc.py
/usr/lib/scons-3.0.1/SCons/Tool/clang.py
/usr/lib/scons-3.0.1/SCons/Tool/clangxx.py
/usr/lib/scons-3.0.1/SCons/Tool/cvf.py
/usr/lib/scons-3.0.1/SCons/Tool/cxx.py
/usr/lib/scons-3.0.1/SCons/Tool/cyglink.py
/usr/lib/scons-3.0.1/SCons/Tool/default.py
/usr/lib/scons-3.0.1/SCons/Tool/dmd.py
/usr/lib/scons-3.0.1/SCons/Tool/docbook/__init__.py
/usr/lib/scons-3.0.1/SCons/Tool/dvi.py
/usr/lib/scons-3.0.1/SCons/Tool/dvipdf.py
/usr/lib/scons-3.0.1/SCons/Tool/dvips.py
/usr/lib/scons-3.0.1/SCons/Tool/f03.py
/usr/lib/scons-3.0.1/SCons/Tool/f08.py
/usr/lib/scons-3.0.1/SCons/Tool/f77.py
/usr/lib/scons-3.0.1/SCons/Tool/f90.py
/usr/lib/scons-3.0.1/SCons/Tool/f95.py
/usr/lib/scons-3.0.1/SCons/Tool/filesystem.py
/usr/lib/scons-3.0.1/SCons/Tool/fortran.py
/usr/lib/scons-3.0.1/SCons/Tool/g++.py
/usr/lib/scons-3.0.1/SCons/Tool/g77.py
/usr/lib/scons-3.0.1/SCons/Tool/gas.py
/usr/lib/scons-3.0.1/SCons/Tool/gcc.py
/usr/lib/scons-3.0.1/SCons/Tool/gdc.py
/usr/lib/scons-3.0.1/SCons/Tool/gettext_tool.py
/usr/lib/scons-3.0.1/SCons/Tool/gfortran.py
/usr/lib/scons-3.0.1/SCons/Tool/gnulink.py
/usr/lib/scons-3.0.1/SCons/Tool/gs.py
/usr/lib/scons-3.0.1/SCons/Tool/gxx.py
/usr/lib/scons-3.0.1/SCons/Tool/hpc++.py
/usr/lib/scons-3.0.1/SCons/Tool/hpcc.py
/usr/lib/scons-3.0.1/SCons/Tool/hpcxx.py
/usr/lib/scons-3.0.1/SCons/Tool/hplink.py
/usr/lib/scons-3.0.1/SCons/Tool/icc.py
/usr/lib/scons-3.0.1/SCons/Tool/icl.py
/usr/lib/scons-3.0.1/SCons/Tool/ifl.py
/usr/lib/scons-3.0.1/SCons/Tool/ifort.py
/usr/lib/scons-3.0.1/SCons/Tool/ilink.py
/usr/lib/scons-3.0.1/SCons/Tool/ilink32.py
/usr/lib/scons-3.0.1/SCons/Tool/install.py
/usr/lib/scons-3.0.1/SCons/Tool/intelc.py
/usr/lib/scons-3.0.1/SCons/Tool/ipkg.py
/usr/lib/scons-3.0.1/SCons/Tool/jar.py
/usr/lib/scons-3.0.1/SCons/Tool/javac.py
/usr/lib/scons-3.0.1/SCons/Tool/javah.py
/usr/lib/scons-3.0.1/SCons/Tool/latex.py
/usr/lib/scons-3.0.1/SCons/Tool/ldc.py
/usr/lib/scons-3.0.1/SCons/Tool/lex.py
/usr/lib/scons-3.0.1/SCons/Tool/link.py
/usr/lib/scons-3.0.1/SCons/Tool/linkloc.py
/usr/lib/scons-3.0.1/SCons/Tool/m4.py
/usr/lib/scons-3.0.1/SCons/Tool/masm.py
/usr/lib/scons-3.0.1/SCons/Tool/midl.py
/usr/lib/scons-3.0.1/SCons/Tool/mingw.py
/usr/lib/scons-3.0.1/SCons/Tool/msgfmt.py
/usr/lib/scons-3.0.1/SCons/Tool/msginit.py
/usr/lib/scons-3.0.1/SCons/Tool/msgmerge.py
/usr/lib/scons-3.0.1/SCons/Tool/mslib.py
/usr/lib/scons-3.0.1/SCons/Tool/mslink.py
/usr/lib/scons-3.0.1/SCons/Tool/mssdk.py
/usr/lib/scons-3.0.1/SCons/Tool/msvc.py
/usr/lib/scons-3.0.1/SCons/Tool/msvs.py
/usr/lib/scons-3.0.1/SCons/Tool/mwcc.py
/usr/lib/scons-3.0.1/SCons/Tool/mwld.py
/usr/lib/scons-3.0.1/SCons/Tool/nasm.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/__init__.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/ipk.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/msi.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/rpm.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/src_tarbz2.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/src_targz.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/src_zip.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/tarbz2.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/targz.py
/usr/lib/scons-3.0.1/SCons/Tool/packaging/zip.py
/usr/lib/scons-3.0.1/SCons/Tool/pdf.py
/usr/lib/scons-3.0.1/SCons/Tool/pdflatex.py
/usr/lib/scons-3.0.1/SCons/Tool/pdftex.py
/usr/lib/scons-3.0.1/SCons/Tool/qt.py
/usr/lib/scons-3.0.1/SCons/Tool/rmic.py
/usr/lib/scons-3.0.1/SCons/Tool/rpcgen.py
/usr/lib/scons-3.0.1/SCons/Tool/rpm.py
/usr/lib/scons-3.0.1/SCons/Tool/rpmutils.py
/usr/lib/scons-3.0.1/SCons/Tool/sgiar.py
/usr/lib/scons-3.0.1/SCons/Tool/sgic++.py
/usr/lib/scons-3.0.1/SCons/Tool/sgicc.py
/usr/lib/scons-3.0.1/SCons/Tool/sgicxx.py
/usr/lib/scons-3.0.1/SCons/Tool/sgilink.py
/usr/lib/scons-3.0.1/SCons/Tool/sunar.py
/usr/lib/scons-3.0.1/SCons/Tool/sunc++.py
/usr/lib/scons-3.0.1/SCons/Tool/suncc.py
/usr/lib/scons-3.0.1/SCons/Tool/suncxx.py
/usr/lib/scons-3.0.1/SCons/Tool/sunf77.py
/usr/lib/scons-3.0.1/SCons/Tool/sunf90.py
/usr/lib/scons-3.0.1/SCons/Tool/sunf95.py
/usr/lib/scons-3.0.1/SCons/Tool/sunlink.py
/usr/lib/scons-3.0.1/SCons/Tool/swig.py
/usr/lib/scons-3.0.1/SCons/Tool/tar.py
/usr/lib/scons-3.0.1/SCons/Tool/tex.py
/usr/lib/scons-3.0.1/SCons/Tool/textfile.py
/usr/lib/scons-3.0.1/SCons/Tool/tlib.py
/usr/lib/scons-3.0.1/SCons/Tool/wix.py
/usr/lib/scons-3.0.1/SCons/Tool/xgettext.py
/usr/lib/scons-3.0.1/SCons/Tool/yacc.py
/usr/lib/scons-3.0.1/SCons/Tool/zip.py
/usr/lib/scons-3.0.1/SCons/Util.py
/usr/lib/scons-3.0.1/SCons/Variables/BoolVariable.py
/usr/lib/scons-3.0.1/SCons/Variables/EnumVariable.py
/usr/lib/scons-3.0.1/SCons/Variables/ListVariable.py
/usr/lib/scons-3.0.1/SCons/Variables/PackageVariable.py
/usr/lib/scons-3.0.1/SCons/Variables/PathVariable.py
/usr/lib/scons-3.0.1/SCons/Variables/__init__.py
/usr/lib/scons-3.0.1/SCons/Warnings.py
/usr/lib/scons-3.0.1/SCons/__init__.py
/usr/lib/scons-3.0.1/SCons/compat/__init__.py
/usr/lib/scons-3.0.1/SCons/compat/_scons_dbm.py
/usr/lib/scons-3.0.1/SCons/cpp.py
/usr/lib/scons-3.0.1/SCons/dblite.py
/usr/lib/scons-3.0.1/SCons/exitfuncs.py
/usr/lib/scons-3.0.1/scons-3.0.1-py2.7.egg-info

%files bin
%defattr(-,root,root,-)
/usr/bin/scons
/usr/bin/scons-3.0.1
/usr/bin/scons-configure-cache
/usr/bin/scons-configure-cache-3.0.1
/usr/bin/scons-time
/usr/bin/scons-time-3.0.1
/usr/bin/sconsign
/usr/bin/sconsign-3.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scons/LICENSE.txt

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/scons-time.1
/usr/share/man/man1/scons.1
/usr/share/man/man1/sconsign.1
